/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class andoop_android_amstory_jni_AudioDataProcessor */

#ifndef _Included_andoop_android_amstory_jni_AudioDataProcessor
#define _Included_andoop_android_amstory_jni_AudioDataProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     andoop_android_amstory_jni_AudioDataProcessor
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_andoop_android_amstory_jni_AudioDataProcessor_test
  (JNIEnv *, jobject);

/*
 * Class:     andoop_android_amstory_jni_AudioDataProcessor
 * Method:    reduceToPercent
 * Signature: ([SI)[S
 */
JNIEXPORT jshortArray JNICALL Java_andoop_android_amstory_jni_AudioDataProcessor_reduceToPercent
  (JNIEnv *, jclass, jshortArray,jshortArray, jint);

/*
 * Class:     andoop_android_amstory_jni_AudioDataProcessor
 * Method:    mixAudioData
 * Signature: ([SIIZ)[S
 */
JNIEXPORT jshortArray JNICALL Java_andoop_android_amstory_jni_AudioDataProcessor_mixAudioData
  (JNIEnv *, jclass, jshortArray,jshortArray, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
